server:
  port: 8999

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: User-Service
                fallbackuri: forward:/userServiceFallBack

        - id: Contact-Service
          uri: lb://Contact-Service
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: Contact-Service
                fallbackuri: forward:/contactServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillieseconds: 50000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
